import {
  REACT_APP_MORALIS_APPLICATION_ID,
  REACT_APP_MORALIS_SERVER_URL,
  REACT_APP_INSTAGRAM_APP_ID,
  REACT_APP_INSTAGRAM_APP_SECRET,
  REACT_APP_INSTAGRAM_REDIRECT_URI,
  REACT_APP_NFT_ITEM_ADDRESS,
  REACT_APP_NFT_AUCTION_ADDRESS,
  REACT_APP_CHAIN_ID,
} from "@env";

export const Config = {
  instagramAppId: REACT_APP_INSTAGRAM_APP_ID,
  instagramAppSecret: REACT_APP_INSTAGRAM_APP_SECRET,
  instagramRedirectUri: REACT_APP_INSTAGRAM_REDIRECT_URI,
  moralisServerUrl: REACT_APP_MORALIS_SERVER_URL,
  moralisApplicationId: REACT_APP_MORALIS_APPLICATION_ID,
  nftItemAddress: REACT_APP_NFT_ITEM_ADDRESS,
  nftAuctionAddress: REACT_APP_NFT_AUCTION_ADDRESS,
  chainId: REACT_APP_CHAIN_ID,
};
